version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - eventcore-net

  api-gateway:
    image: api-gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - user-service
    networks:
      - eventcore-net

  user-service:
    image: user-service:latest
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - eventcore-net

  frontend:
    image: frontend:latest
    ports:
      - "8031:80"
    depends_on:
      - api-gateway
    networks:
      - eventcore-net

volumes:
  pgdata:

networks:
  eventcore-net:
