server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://user-service:8081
              predicates:
                - Path=/api/users/**
                - Path=/avatars/**
              filters:
                - StripPrefix=1
            - id: frontend
              uri: http://frontend:80
              predicates:
                - Path=/**
